# Generated by Django 4.2 on 2024-07-23 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_alter_agent_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="token",
            field=models.CharField(
                db_index=True,
                default="a_151949a2-3029-4600-a546-565d5464d3ae",
                max_length=255,
                unique=True,
            ),
        ),
    ]
