# Generated by Django 4.2 on 2024-07-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_agent_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='token',
            field=models.CharField(db_index=True, default='a_be2c824c-8265-4890-a898-a2b1e8d9d04b', max_length=255, unique=True),
        ),
    ]
